# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:            Vulmon Blog
email:            info@vulmon.com
description:      Vulmon Blog. Vulmon is a vulnerability and exploit search engine with vulnerability intelligence features.
baseurl:          '' # The subpath of your site, e.g. /blog
url:              'https://blog.vulmon.com' # The base hostname & protocol for your site
github_username:  vulmon
twitter_username: vulmoncom

markdown:  kramdown
permalink: pretty
paginate:  12
sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  yavuz:
    name:             Yavuz Atlas
    bio:              Founder of Vulmon Project. Cyber security researcher and software developer.
    gravatar:         https://gravatar.com/avatar/78e46a30fdf0559bbb93c93652e5e887?s=200
    email:            yavuz.atlas@vulmon.com
    website:          https://vulmon.com
    github_username:  yavuzatlas
    twitter_username: yavuzatlas_
    linkedin_username: yavuzatlas